services:
  backend:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload
    ports:
      - "8001:8001"
    env_file: .env
    environment:
      APP_ENV: development
      DATABASE_URL: postgresql+asyncpg://supermarket:password@postgres:5432/supermarket_db
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
      CV_ENGINE_URL: http://cv-engine:8000
    volumes:
      - ./app:/app/app
      - ./alembic:/app/alembic
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      cv-engine:
        condition: service_started
    networks:
      - supermarket-net

  celery-worker:
    build: .
    command: celery -A app.workers.celery_app worker --loglevel=debug --concurrency=1
    env_file: .env
    environment:
      APP_ENV: development
      DATABASE_URL: postgresql+asyncpg://supermarket:password@postgres:5432/supermarket_db
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
      CV_ENGINE_URL: http://cv-engine:8000
    volumes:
      - ./app:/app/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - supermarket-net

  celery-beat:
    build: .
    command: celery -A app.workers.celery_app beat --loglevel=debug
    env_file: .env
    environment:
      APP_ENV: development
      DATABASE_URL: postgresql+asyncpg://supermarket:password@postgres:5432/supermarket_db
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
    volumes:
      - ./app:/app/app
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - supermarket-net

  cv-engine:
    build: ../Heatmaps-Generation-CNN
    ports:
      - "8000:8000"
    networks:
      - supermarket-net

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: supermarket
      POSTGRES_PASSWORD: password
      POSTGRES_DB: supermarket_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U supermarket -d supermarket_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - supermarket-net

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - supermarket-net

volumes:
  postgres_data:

networks:
  supermarket-net:
    driver: bridge
